exportFilePath: X:\game\platform\pc\Ultimate Marvel vs. Capcom 3\nativePCx64\chr\archive\0001_00\chr\Ryu\model\1p\Ryu.58a15856.mod
exportGroups: true
exportMetadataPath: X:\project\umvc3_model\repo\src\python\mtio\modules\mtlib/res/metadata/Ryu.yml
exportMrlYml: false
exportMrlYmlPath: X:\project\umvc3_model\samples\UMVC3ModelSamples\Ryu - Copy\Ryu.mrl.yml
exportNormals: false
exportPml: true
exportPrimitives: true
exportRefPath: X:\project\umvc3_model\samples\UMVC3ModelSamples\Ryu - Copy\Ryu.mod
exportSkeleton: true
exportTexturesToTex: false
exportUseRefBounds: true
exportUseRefGroups: true
exportUseRefJoints: true
exportUseRefPml: true
exportWeights: false
flipUpAxis: false
importConvertTexturesToDDS: true
importFilePath: X:\project\umvc3_model\samples\UMVC3ModelSamples\Ryu - Copy\Ryu.mod
importGroups: true
importMetadataPath: X:\project\umvc3_model\repo\src\python\mtio\modules\mtlib/res/metadata/Ryu.yml
importNormals: true
importPrimitives: true
importSaveMrlYml: true
importSkeleton: true
importWeights: true
scale: 1
